mm: vmscan: Add a debug file for shrinkers
This patch adds a debugfs file called "shrinker" when read this calls
all the shrinkers in the system with nr_to_scan set to zero and prints
the result.  These results are the number of objects the shrinkers have
available and can thus be used an indication of the total memory
that would be availble to the system if a shrink occurred.

Change-Id: Ied0ee7caff3d2fc1cb4bb839aaafee81b5b0b143
Signed-off-by: Rebecca Schultz Zavin <rebecca@android.com>

Conflicts:
	mm/vmscan.c

Updated: Compile fails with:
	mm/vmscan.c: In function ‘debug_shrinker_show’:
	mm/vmscan.c:194:22: error: ‘struct shrinker’ has no member named ‘shrink’
	mm/vmscan.c:195:37: error: ‘struct shrinker’ has no member named ‘shrink’
	mm/vmscan.c:191:8: warning: unused variable ‘name’ [-Wunused-variable]

	I made trivial change in patch to fix compile errors and warning.

Signed-off-by: Tushar Dave <tushar.n.dave@intel.com>