make sure it is due to USB team after modify code in sep_sysfs.c pls see log on BZ
BZ: 175621

ARKHAM-1690:Summary:[CTS]android.permission.cts.FileSystemPermissionTes
Problem:
1.modigfy code linux/kernel/drivers/staging/sep54/sep_sysfs.c
2.Run CTS android.permission.cts.FileSystemPermissionTest on saltbay ,error log below
junit.framework.AssertionFailedError: Found writable: [/sys/kernel/debug/usb/hsic/host_resume]
3.the issue is on USB dir folder so turn to usb team to check

Solution: modify the sep_sysfs.c change line 305'0666'to'0664'

Change-Id: Ib8be6a60f46dc2e887e570f110b5344e74b2afc1
Category: feature differentiation
Domain: AOSP.Security-Arkham
Origin: internal
Upstream-Candidate: no, proprietary
Signed-off-by: jiangyax <jiangx.yao@intel.com>